# Generated by Django 5.2.3 on 2025-06-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
